/**
 * `MockNarrativeProvider` — deterministic, in-process implementation of
 * `NarrativeProvider` used in tests and local development. Returns a
 * Zod-validated `NarrativeData` derived from the input snapshot so the
 * downstream UI / cache plumbing can be exercised without a real LLM key.
 *
 * Pure function of the input — same `NarrativeInput` always produces the
 * same `NarrativeData` (modulo `generatedAt`, which the caller may pin via
 * the `now` injection point for stable snapshots in tests).
 */
import {
  NarrativeDataSchema,
  type NarrativeData,
  type NarrativeInput,
  type NarrativeProvider,
  type Result,
  err,
  ok,
} from "@darkscore/types";
import { NarrativeError } from "./errors.js";

export interface MockNarrativeProviderOptions {
  readonly name?: string;
  readonly model?: string;
  readonly now?: () => Date;
}

export class MockNarrativeProvider implements NarrativeProvider {
  readonly name: string;
  readonly model: string;
  private readonly now: () => Date;

  constructor(options: MockNarrativeProviderOptions = {}) {
    this.name = options.name ?? "mock";
    this.model = options.model ?? "mock-1";
    this.now = options.now ?? (() => new Date());
  }

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async generate(input: NarrativeInput): Promise<Result<NarrativeData>> {
    const symbol = input.ticker.symbol.toUpperCase();
    const price = input.ticker.currentPrice;
    const candidate: NarrativeData = {
      cardSubtitles: {
        valuationPe: `Mock P/E commentary for ${symbol}`,
        valuationEv: `Mock EV/EBITDA commentary for ${symbol}`,
        valuationRelative: `Mock peer-relative valuation note for ${symbol}`,
        healthBalance: `Mock balance-sheet snapshot for ${symbol}`,
        healthCashFlow: `Mock cash-flow note for ${symbol}`,
        healthProfitability: `Mock profitability note for ${symbol}`,
        growthRevenue: `Mock revenue-growth note for ${symbol}`,
        growthSegment: `Mock segment-mix note for ${symbol}`,
        growthEarnings: `Mock earnings-trajectory note for ${symbol}`,
      },
      chartAnnotations: [
        {
          date: input.priceHistory[0]?.date ?? this.now().toISOString().slice(0, 10),
          label: "Mock event",
          kind: "event",
        },
      ],
      catalysts: [
        `Mock catalyst A for ${symbol}`,
        `Mock catalyst B for ${symbol}`,
        `Mock catalyst C for ${symbol}`,
      ],
      risks: [
        `Mock risk A for ${symbol}`,
        `Mock risk B for ${symbol}`,
        `Mock risk C for ${symbol}`,
      ],
      priceTargets: {
        bear: round(price * 0.8),
        base: round(price * 1.0),
        bull: round(price * 1.25),
      },
      verdict: {
        headline: `Mock verdict for ${symbol}`,
        paragraph: `This is a deterministic mock verdict generated for ${symbol} from the supplied report snapshot. It is not investment advice.`,
      },
      disclaimer:
        "Generated by MockNarrativeProvider for testing only. Not investment advice.",
      providerName: this.name,
      model: this.model,
      generatedAt: this.now().toISOString(),
    };

    const parsed = NarrativeDataSchema.safeParse(candidate);
    if (!parsed.success) {
      return err(
        new NarrativeError(
          this.name,
          "SCHEMA",
          "MockNarrativeProvider produced data that failed schema validation",
          parsed.error.message,
        ),
      );
    }
    return ok(parsed.data);
  }
}

function round(n: number): number {
  return Math.round(n * 100) / 100;
}

