"use client";
/**
 * Floating "Copy Report" button — serializes a ReportData into a
 * plain-text summary and writes it to the system clipboard. Toast pops in,
 * fades out after ~2s. Mirrors the legacy `copyReport()` script.
 *
 * Marked client-only because it owns onClick + transient UI state. The
 * plain-text builder lives above the JSX so the component body stays a
 * thin presentational shell (C12).
 */
import { useState } from "react";
import type { ReportData } from "@darkscore/types";
import { NOT_AVAILABLE } from "../../lib/format";

type ToastState = "idle" | "ok" | "error";

interface ClipboardExportProps {
  readonly reportData: ReportData;
}

const REVENUE_FORMATTER = new Intl.NumberFormat("en-US", {
  notation: "compact",
  maximumFractionDigits: 1,
});

function formatRevenue(value: number): string {
  return `$${REVENUE_FORMATTER.format(value)}`;
}

function buildSummary(data: ReportData): string {
  const { ticker, riskScore, financials, keyMetrics, verdict } = data;
  const targets = verdict.priceTargets;
  const peTtm =
    keyMetrics.peRatioTTM !== null ? `${keyMetrics.peRatioTTM.toFixed(1)}x` : NOT_AVAILABLE;
  const peFwd =
    keyMetrics.peRatioForward !== null
      ? `${keyMetrics.peRatioForward.toFixed(1)}x`
      : NOT_AVAILABLE;
  return [
    `${ticker.symbol} DARK RISK SCORE REPORT`,
    "===========================",
    `${ticker.name} (${ticker.symbol})`,
    "",
    `RISK SCORE: ${riskScore.composite}/100 — ${riskScore.riskLabel}`,
    `Rating: ${riskScore.rating.replace(/_/g, " ")}`,
    "",
    "KEY METRICS",
    `• P/E (TTM): ${peTtm} | Fwd P/E: ${peFwd}`,
    `• Revenue TTM: ${formatRevenue(financials.revenueTTM)} | Net Margin: ${financials.netMargin.toFixed(1)}%`,
    `• EPS TTM: $${financials.epsTTM.toFixed(2)}`,
    "",
    `PRICE TARGETS: Bear $${targets.bear.toFixed(0)} | Base $${targets.base.toFixed(0)} | Bull $${targets.bull.toFixed(0)}`,
    "",
    verdict.summary,
    "",
    "Generated by Dark Risk Score Engine",
  ].join("\n");
}

export function ClipboardExport({
  reportData,
}: ClipboardExportProps): JSX.Element {
  const [toast, setToast] = useState<ToastState>("idle");

  async function handleCopy(): Promise<void> {
    try {
      await navigator.clipboard.writeText(buildSummary(reportData));
      setToast("ok");
      setTimeout(() => setToast("idle"), 2000);
    } catch (err) {
      console.error("Copy failed", err);
      setToast("error");
      setTimeout(() => setToast("idle"), 2500);
    }
  }

  const visible = toast !== "idle";
  const isError = toast === "error";
  const message = isError
    ? "Copy failed — clipboard unavailable"
    : "Copied to clipboard ✓";
  const toneClass = isError
    ? "bg-[#ff4757] text-white"
    : "bg-[#00dc82] text-black";

  return (
    <>
      <button
        type="button"
        onClick={() => {
          void handleCopy();
        }}
        className="fixed bottom-6 right-6 z-50 px-5 py-3 rounded-lg bg-[#3b82f6] text-white text-sm font-semibold shadow-[0_4px_20px_rgba(59,130,246,0.35)] hover:-translate-y-0.5 hover:shadow-[0_6px_28px_rgba(59,130,246,0.45)] transition-transform"
        title="Copy Report"
      >
        📋 Copy Report
      </button>
      <div
        role="status"
        aria-live="polite"
        className={`fixed bottom-20 right-6 z-50 px-5 py-2.5 rounded-md text-xs font-semibold pointer-events-none transition-all duration-300 ${toneClass} ${
          visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-2.5"
        }`}
      >
        {message}
      </div>
    </>
  );
}

